#!/bin/sh

portsnap fetch
portsnap extract
portsnap update

#portversion
#portupgrade nmap-5.61.t2
#portupgrade -aR
#portsclean -CD

mkdir /usr/ports/packages

cd /usr/ports/shells/bash/ && make BATCH=yes install
cd /usr/ports/devel/libtool && make all && make BATCH=yes install
cd /usr/ports/textproc/expat2 && make BATCH=yes install
cd /usr/ports/devel/gmake && make BATCH=yes install
cd /usr/ports/security/sudo && make BATCH=yes install
cd /usr/ports/net/isc-dhcp42-server/ && make WITHOUT_DHCP_PARANOIA=yes BATCH=yes install
#cd /usr/ports/www/apache22/ && make BATCH=yes install
cd /usr/ports/databases/mysql51-server/ && make BATCH=yes install
cd /usr/ports/lang/php5 && make WITH_CLI=yes WITH_APACHE=yes BATCH=yes install
cd /usr/ports/lang/php5-extensions/ && make WITH_MYSQL=yes WITH_MBSTRING=yes WITH_ICONV=yes WITH_GD=yes WITH_BCMATH=yes WITH_XML=yes BATCH=yes install
cd /usr/ports/net/arping/ && make BATCH=yes install
cd /usr/ports/net-mgmt/bandwidthd/ && make BATCH=yes install
cd /usr/ports/net-mgmt/softflowd/ && make BATCH=yes install
cd /usr/ports/ports-mgmt/portupgrade/ && make BATCH=yes install
#cd /usr/ports/dns/pdnsd/ && make BATCH=yes install
