#!/bin/sh

# PROVIDE: bandwidthd

. /etc/rc.subr

name="bandwidthd"
rcvar="${name}_enable"

load_rc_config "${name}"

required_dirs=""
required_files=""

command="/usr/local/${name}/${name}"
command_args=""

run_rc_command "$1"
