#!/bin/sh

# PROVIDE: stargazer

. /etc/rc.subr

name="stargazer"
rcvar="${name}_enable"

load_rc_config "${name}"

required_dirs=""
required_files="/etc/${name}/${name}.conf"

command="/usr/sbin/${name}"
command_args=""

run_rc_command "$1"
