INSERT INTO city VALUES("1","Северск","svrsk");
INSERT INTO street VALUES("1","1","Артема","artema");
INSERT INTO street VALUES("2","1","Бахмутская","bahmutskaja");
INSERT INTO street VALUES("3","1","Безымянная","bezymjannaja");
INSERT INTO street VALUES("4","1","Богдана Хмельницкого","bogdana_hmelnickogo");
INSERT INTO street VALUES("5","1","Виноградная","vinogradnaja");
INSERT INTO street VALUES("6","1","Гагарина","gagarina");
INSERT INTO street VALUES("7","1","Гоголя","gogolja");
INSERT INTO street VALUES("8","1","Горького","gorkogo");
INSERT INTO street VALUES("9","1","Дзержинского","dzerzhinskogo");
INSERT INTO street VALUES("10","1","Димитрова","dimitrova");
INSERT INTO street VALUES("11","1","Донецкая","doneckaja");
INSERT INTO street VALUES("12","1","Железнодорожная","zheleznodorozhnaja");
INSERT INTO street VALUES("13","1","Заречная","zarechnaja");
INSERT INTO street VALUES("14","1","Зои Космодемьянской","zoi_kosmodemjanskoj");
INSERT INTO street VALUES("15","1","Карла Либкнехта","karla_libknehta");
INSERT INTO street VALUES("16","1","Карла Маркса","karla_marksa");
INSERT INTO street VALUES("17","1","Кирова","kirova");
INSERT INTO street VALUES("18","1","Колесникова","kolesnikova");
INSERT INTO street VALUES("19","1","Колхозная","kolhoznaja");
INSERT INTO street VALUES("20","1","Комсомольская","komsomolskaja");
INSERT INTO street VALUES("21","1","Коцюбинского","kocjubinskogo");
INSERT INTO street VALUES("22","1","Кошевого","koshevogo");
INSERT INTO street VALUES("23","1","Красноармейская","krasnoarmejskaja");
INSERT INTO street VALUES("24","1","Крупской","krupskoj");
INSERT INTO street VALUES("25","1","Куйбышева","kujbysheva");
INSERT INTO street VALUES("26","1","Кутузова","kutuzova");
INSERT INTO street VALUES("27","1","Ленина","lenina");
INSERT INTO street VALUES("28","1","Ленина просп.","lenina_prosp");
INSERT INTO street VALUES("29","1","Лермонтова","lermontova");
INSERT INTO street VALUES("30","1","Матросова","matrosova");
INSERT INTO street VALUES("31","1","Маяковского","majakovskogo");
INSERT INTO street VALUES("32","1","Межинского","mezhinskogo");
INSERT INTO street VALUES("33","1","Менделеева","mendeleeva");
INSERT INTO street VALUES("34","1","Молодежная","molodezhnaja");
INSERT INTO street VALUES("35","1","Набережная","naberezhnaja");
INSERT INTO street VALUES("36","1","Нахимова","nahimova");
INSERT INTO street VALUES("37","1","Нижняя","nizhnjaja");
INSERT INTO street VALUES("38","1","Октябрьская","oktjabrskaja");
INSERT INTO street VALUES("39","1","Орджоникидзе","ordzhonikidze");
INSERT INTO street VALUES("40","1","Островского","ostrovskogo");
INSERT INTO street VALUES("41","1","Павлова","pavlova");
INSERT INTO street VALUES("42","1","Первомайская","pervomajskaja");
INSERT INTO street VALUES("43","1","Пионерская","pionerskaja");
INSERT INTO street VALUES("44","1","Победы","pobedy");
INSERT INTO street VALUES("45","1","Полевая","polevaja");
INSERT INTO street VALUES("46","1","Почтовая","pochtovaja");
INSERT INTO street VALUES("47","1","Прибрежная","pribrezhnaja");
INSERT INTO street VALUES("48","1","Пролетарская","proletarskaja");
INSERT INTO street VALUES("49","1","Пушкина","pushkina");
INSERT INTO street VALUES("50","1","Рабочая","rabochaja");
INSERT INTO street VALUES("51","1","Радионовских Патриотов","radionovskih_patriotov");
INSERT INTO street VALUES("52","1","Садовая","sadovaja");
INSERT INTO street VALUES("53","1","Свердлова","sverdlova");
INSERT INTO street VALUES("54","1","Северная","severnaja");
INSERT INTO street VALUES("55","1","Сельскохозяйственная","selskohozjajstvennaja");
INSERT INTO street VALUES("56","1","Советский пер.","sovetskij_per");
INSERT INTO street VALUES("57","1","Сосюры","sosjury");
INSERT INTO street VALUES("58","1","Суворова","suvorova");
INSERT INTO street VALUES("59","1","Толстого","tolstogo");
INSERT INTO street VALUES("60","1","Циолковского","ciolkovskogo");
INSERT INTO street VALUES("61","1","Чапаева","chapaeva");
INSERT INTO street VALUES("62","1","Чернышевского","chernyshevskogo");
INSERT INTO street VALUES("63","1","Чехова","chehova");
INSERT INTO street VALUES("64","1","Чкалова","chkalova");
INSERT INTO street VALUES("65","1","Шевченко","shevchenko");
INSERT INTO street VALUES("66","1","Школьная","shkolnaja");
INSERT INTO street VALUES("67","1","Энгельса","jengelsa");
INSERT INTO street VALUES("68","1","Юбилейная","jubilejnaja");
INSERT INTO street VALUES("69","1","Южная","juzhnaja");